import dotenv from 'dotenv';
dotenv.config();

export const config = {
  PORT: process.env.PORT ? parseInt(process.env.PORT, 10) : 3000,
  NODE_ENV: process.env.NODE_ENV || 'development',
  API_KEY_SECRET: process.env.API_KEY_SECRET || 'change-me',
  RAPIDAPI_PROXY_SECRET: process.env.RAPIDAPI_PROXY_SECRET || '',
  // Public base URL advertised in the OpenAPI spec, so the "Try it" button in
  // Swagger UI and on RapidAPI points at the deployed API rather than localhost.
  // RENDER_EXTERNAL_URL is injected automatically on Render, so a deploy there
  // advertises its own URL without any extra configuration.
  PUBLIC_URL: process.env.PUBLIC_URL || process.env.RENDER_EXTERNAL_URL || '',
};

/**
 * Where the served data comes from. The current dataset is generated by
 * src/db/seed.ts for development and to demonstrate the API's shape; it is not
 * sourced from JoSAA, MCC or NIRF. Change this only when real data replaces it.
 */
export const DATA_PROVENANCE = {
  source: 'synthetic' as const,
  notice:
    'Sample data: every cutoff, ranking, placement and exam statistic is synthetically generated to demonstrate the API and does not reflect official JoSAA, MCC or NIRF figures. Do not use it for admission decisions.',
};
